[update_manager helixscreen]
type: web
channel: stable
repo: prestonbrown/helixscreen
path: /srv/helixscreen
persistent_files:
    config/helixconfig.json

[update_manager flook32]
type: git_repo
channel: stable
path: /root/printer_data/config/mod_data/plugins/flook32
origin: https://github.com/ghzserg/flook32_plugin.git
is_system_service: False
primary_branch: main
