#!/bin/sh
# (C) 2024-2026 ghzserg https://github.com/ghzserg/zmod
#
# Starts busbox httpd
#

source /usr/data/zmod/zmod/.shell/0.sh

PID_FILE=/run/httpd.pid

CLIENT="fluidd"

[ -f /opt/config/mod_data/web.conf ] || echo "# Не редактируйте этот файл
# Используйте макрос
#
# WEB
#

CLIENT=${CLIENT}" > /opt/config/mod_data/web.conf

source /opt/config/mod_data/web.conf

WEBROOT=/root/$CLIENT

sed "s/    \"defaultLocale\": \"ru\",/    \"defaultLocale\": \"${ZLANG}\",/" /usr/data/zmod/zmod/.shell/root/config.json >/root/mainsail/config.json

cp /usr/data/zmod/zmod/.shell/.theme/sidebar-logo.svg /root/fluidd/logo_fluidd.svg

start() {
    if [ "${C5PRO}" = "1" ] || [ "${AD5X}" = "1" ]; then
        if ! grep -q "web_screen = 0" /opt/config/mod_data/variables.cfg; then
            mkdir -p /root/nginx/client-body /root/nginx/proxy
            sed -e "s/fluidd/${CLIENT}/g" -e "s/mainsail/${CLIENT}/g" /usr/data/zmod/zmod/.shell/root/nginx/nginx.conf > /root/nginx/nginx.conf
            /usr/data/zmod/zmod/.shell/root/nginx/nginx -c /root/nginx/nginx.conf -e /opt/config/mod_data/log/nginx.log
            exit 0
        fi
    fi
    start-stop-daemon -S -b -m -p $PID_FILE --exec /usr/data/zmod/zmod/.shell/root/zmod_httpd -- $WEBROOT
}

stop() {
    killall zmod_httpd
    killall httpd
    killall nginx
    start-stop-daemon -K -p $PID_FILE
}
restart() {
    stop
    sleep 1
    start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
