#!/bin/sh
# (C) 2024-2026 ghzserg https://github.com/ghzserg/zmod
#
# Starts busbox httpd
#

source /usr/data/zmod/zmod/.shell/0.sh

PID_FILE=/run/httpd.pid

CLIENT="fluidd"

[ -f /opt/config/mod_data/web.conf ] || echo "# Не редактируйте этот файл
# Используйте макрос
#
# WEB
#

CLIENT=${CLIENT}" > /opt/config/mod_data/web.conf

source /opt/config/mod_data/web.conf

WEBROOT=/root/$CLIENT

sed "s/    \"defaultLocale\": \"ru\",/    \"defaultLocale\": \"${ZLANG}\",/" /usr/data/zmod/zmod/.shell/root/config.json >/root/mainsail/config.json

cp /usr/data/zmod/zmod/.shell/.theme/sidebar-logo.svg /root/fluidd/logo_fluidd.svg

start() {
    if [ ${C5PRO} -eq 1 ]; then
        cat /usr/data/zmod/zmod/.shell/root/web.cfg | sed "s/fluidd/${CLIENT}/"| sed "s/mainsail/${CLIENT}/" >/root/web.cfg
        /usr/data/zmod/zmod/.shell/zremote.sh /usr/prog/nginx/sbin/nginx -p /usr/prog/nginx -c /usr/prog/nginx/conf/nginx.conf
    else
        # start busybox httpd
        #if [ "$CLIENT" == "mainsail" ]; then
            start-stop-daemon -S -b -m -p $PID_FILE --exec /usr/data/zmod/zmod/.shell/root/zmod_httpd -- $WEBROOT
        #else
        #    start-stop-daemon -S -b -m -p $PID_FILE --exec httpd -- -p 80 -f -h $WEBROOT -c /usr/data/zmod/zmod/.shell/root/httpd.conf
        #fi
    fi
}

stop() {
    killall zmod_httpd
    killall httpd
    killall nginx
    start-stop-daemon -K -p $PID_FILE
}
restart() {
    stop
    sleep 1
    start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
